[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[window]
decorations = "none"

# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new"]

