# ~/.config/niri/config.toml

# …other sections…

[xwayland]
enable       = true
binary       = "/usr/bin/Xwayland"    # only needed if Xwayland isn’t on $PATH
cursor_theme = "Adwaita"
cursor_size  = 24

